app/controllers/lectures_controller.rb
app/models/lecture.rb
app/models/sprint_lecture.rb
app/views/lectures/_form.html.erb
app/views/lectures/edit.html.erb
app/views/lectures/index.html.erb
app/views/lectures/new.html.erb
app/views/lectures/show.html.erb
test/controllers/lectures_controller_test.rb

Creating the lecture CRUD (index,show,new,create,edit,update,destroy). Adding basic views to test operation.
Adding validations and relationships to the lecture and sprint_lecture tables.
Creating the lecture video player

Feacture/crud lecture sprint lecture/#7

---

Gemfile.lock
app/controllers/clients_controller.rb
app/models/client.rb
app/models/project.rb
app/views/clients/_form.html.erb
app/views/clients/edit.html.erb
app/views/clients/index.html.erb
app/views/clients/new.html.erb
app/views/clients/show.html.erb
config/routes.rb
test/controllers/clients_controller_test.rb

Implementação do crud de clients com views básicas e funcionais.

Feat/client crud/#4

---

app/controllers/tasks_controller.rb
app/models/task.rb
app/views/tasks/_form.html.erb
app/views/tasks/edit.html.erb
app/views/tasks/index.html.erb
app/views/tasks/new.html.erb
app/views/tasks/show.html.erb
test/controllers/tasks_controller_test.rb

- Criação do controller de task e seus métodos
- As respectivas view de task
- Criação de validações e associações

Close : Feature/#6 

---

app/controllers/sprints_controller.rb
app/models/project.rb
app/models/sprint.rb
app/views/sprints/_form.html.erb
app/views/sprints/edit.html.erb
app/views/sprints/index.html.erb
app/views/sprints/new.html.erb
app/views/sprints/show.html.erb
config/routes.rb
test/controllers/sprints_controller_test.rb

CRUD de Sprint
- Associações no modelo de Sprint
- Controller e métodos de Sprint
- Rascunho de Views de Sprint

Close: Feature / #5 CRUD de Sprint

---

app/controllers/tasks_controller.rb
app/controllers/ticket_controller.rb
app/controllers/tickets_controller.rb
app/models/ticket.rb
app/views/tickets/_form.html.erb
app/views/tickets/edit.html.erb
app/views/tickets/index.html.erb
app/views/tickets/new.html.erb
app/views/tickets/show.html.erb
test/controllers/ticket_controller_test.rb

- Criação do controller de ticket e seus métodos
-  As respectivas view de ticket
-  Criação de validações e associações

Close: Feature/#8

---

app/models/sprint.rb

- Adicionada no modelo Sprint a relação com modelo Task
- Adicionadas validações no modelo Sprint

Fix / CRUD Sprint / #6

---

app/assets/stylesheets/components/_card.scss
app/controllers/projects_controller.rb
app/views/projects/sprint.html.erb

**Implementar Small Cards de Sprints**
**Descrição:**
Cria os cards de início da página para Sprints - Full Stack. Além disso, já inicia a lógica backend que será necessária para o(s) main card(s) dá página.
**Motivação:**
A gente decidiu - kkkk
**Pontos de atenção!!**
- precisamos decidir a route desta página. Neste momento é uma view tipo 'member' de Project. Vai ficar assim mesmo?
- precisamos revisar o modelo e views de Tickets

Closes: #43 Sprints - Small Cards

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_table.scss
app/controllers/projects_controller.rb
app/controllers/tickets_controller.rb
app/models/user.rb
app/views/projects/dashboard.html.erb
app/views/tickets/_form.html.erb

Realizei a conexão de todos dados do back com front da tela de dashboard e uma alteração em tickets para se tornar um pouco mais realista sua criação

Close: Feature/#40

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_table.scss
app/assets/stylesheets/components/_tag.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_sprints.scss
app/controllers/sprints_controller.rb
app/models/project.rb
app/models/sprint.rb
app/views/projects/dashboard.html.erb
app/views/projects/index.html.erb
app/views/sprints/_form.html.erb
app/views/sprints/edit.html.erb
app/views/sprints/index.html.erb

Closes primeira versão completa de Sprints
Apontamento: para deletar uma sprint, coloquei o link dentro da view de edit, para ser mais difícil o acesso (não é algo trivial de se deletar). No entanto, o delete quebra quando há alguma lecture conectada à sprint.

Feat/sprints table/#46

---

app/views/projects/dashboard.html.erb

Criação de um if para quando o usuário não tiver projeto a ser exibido no dashboard

Close: Feature#71

---

app/views/projects/show.html.erb

Adding back the layout of the show de projects screen that had been accidentally removed in a conflict

Fix: Conflited

---

config/environments/production.rb

Deploy configuration to heroku, link:
https://protected-castle-90393-a26e5830bda9.herokuapp.com

Feat/configuração para deploy/#83

---

app/controllers/sprint_lectures_controller.rb
app/models/sprint_lecture.rb
app/views/projects/index.html.erb
app/views/projects/myprojects.html.erb
app/views/sprint_lectures/new.html.erb
app/views/sprints/_form.html.erb
app/views/sprints/edit.html.erb
app/views/sprints/index.html.erb
config/routes.rb
db/migrate/20240628164621_rename_project_member_id_to_user_id_in_sprint_lectures_and_allow_null.rb
db/schema.rb
test/controllers/sprintlectures_controller_test.rb

Criação da lógica para pode associar as lectures com um sprint específico

Close: Feature/#60

---

.gitignore
app/assets/config/manifest.js
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_tag.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_task.scss
app/controllers/tasks_controller.rb
app/views/projects/index.html.erb
app/views/projects/myprojects.html.erb
app/views/projects/show.html.erb
app/views/sprints/index.html.erb
app/views/tasks/edit.html.erb
app/views/tasks/new.html.erb
app/views/tasks/show.html.erb
db/schema.rb

- Completa back e front de Show de tasks.

Closes #59

---

app/views/tickets/show.html.erb

feat: Creating a ticket show

---

app/helpers/clients_helper.rb
app/models/client.rb
app/views/clients/index.html.erb
db/migrate/20240710164202_change_is_active_default_to_true_in_projects.rb
db/schema.rb

Closes: #78

---

app/assets/stylesheets/components/_card.scss
app/views/projects/dashboard.html.erb

Adiciona rota de sprints de um projeto na Dashboard e também a data da sprint atual

Closes: Feat/#117

---

app/views/tasks/show.html.erb

Closes: #131

---

app/views/tasks/show.html.erb

Atualiza show de Tasks para que apenas o responsável pela tarefa possa modificar o status dela.

Closes: #130

---

app/controllers/projects_controller.rb
app/views/progress_bars/_sprint_progress_steps.html.erb
app/views/projects/show.html.erb
app/views/sprints/index.html.erb

Ausencia  da rota e da view da show de user, redirecionei para rota de project members para ser mais coerente.

Feat/link ver membro show de user/#125

---

app/controllers/application_controller.rb
app/controllers/clients_controller.rb
app/controllers/lectures_controller.rb
app/controllers/project_members_controller.rb
app/controllers/projects_controller.rb
app/controllers/sprints_controller.rb
app/controllers/tasks_controller.rb
app/views/project_members/index.html.erb
app/views/projects/_form.html.erb
app/views/projects/index.html.erb
app/views/projects/myprojects.html.erb
app/views/shared/_sidebar.html.erb
app/views/tasks/show.html.erb
app/views/tickets/_new_form.html.erb

fix: Minor fixes

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_user_show.scss
app/controllers/application_controller.rb
app/controllers/tasks_controller.rb
app/controllers/users_controller.rb
app/models/sprint.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/projects/show.html.erb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb
config/routes.rb
db/migrate/20240719161207_add_social_fields_to_users.rb
db/schema.rb
test/controllers/users_controller_test.rb

- Cria rota de perfil de usuário
- Adiciona atributos em usuário
- Modifica os forms de usuário para adicição desses novos atributos (links para Linkedin e Github)
- Cria view de perfil de usuário
- Altera rota que estava em Show de Project no link 'ver membro' para a rota de user#show
- Adiciona link para 'Meu Perfil' na navbar

Closes: Feat/user show/#134

---

app/controllers/project_members_controller.rb
app/views/clients/_form.html.erb
app/views/clients/_form_edit.html.erb
app/views/clients/show.html.erb
app/views/project_members/_form.html.erb
app/views/project_members/index.html.erb
app/views/projects/_form.html.erb
app/views/projects/dashboard.html.erb
app/views/projects/edit.html.erb
app/views/projects/new.html.erb
app/views/projects/show.html.erb
app/views/sprints/_form.html.erb
app/views/sprints/index.html.erb
app/views/sprints/new.html.erb
app/views/tasks/_new_form.html.erb
app/views/tasks/show.html.erb
config/routes.rb

- ajusta rota inicial para dashboard
- coloca links para show de usuário em show de Tarefa
- centraliza títulos de páginas, de forma a padronizar todas
- arruma new de task que estava quebrando por conta de uma vírgula faltante
- Padroniza botões de partials que são utilizadas tanto para new quanto para edit
- Adiciona breadcrumbs para index de Project_members, a fim de facilitar entendimento de qual projeto está sendo manejado

Closes: Feat/front refine/#164
